-- Esquema Postgres de precios (Supabase). Equivalente a db/precios.sql.
CREATE SCHEMA IF NOT EXISTS precios;

CREATE TABLE IF NOT EXISTS precios.insumos (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo      TEXT NOT NULL,
    nombre      TEXT NOT NULL,
    nombre_norm TEXT NOT NULL,
    unidad      TEXT,
    grupo       TEXT,
    oculto      BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (codigo, nombre_norm)
);
CREATE INDEX IF NOT EXISTS idx_insumo_cod ON precios.insumos(codigo);

ALTER TABLE precios.insumos ADD COLUMN IF NOT EXISTS oculto BOOLEAN NOT NULL DEFAULT FALSE;

-- Una lista = una tarifa. La id 1 es SIEMPRE 'Principal' (la siembra este script).
-- Va ANTES de precios.insumo_precios para que su columna lista_id (FK) resuelva.
CREATE TABLE IF NOT EXISTS precios.lista_precios (
    -- BY DEFAULT (no ALWAYS): la semilla de abajo inserta el id 1 explícitamente.
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     TEXT NOT NULL UNIQUE,
    creada_en  TEXT NOT NULL,
    creado_por TEXT
);

INSERT INTO precios.lista_precios (id, nombre, creada_en)
SELECT 1, 'Principal', to_char(now(), 'YYYY-MM-DD')
WHERE NOT EXISTS (SELECT 1 FROM precios.lista_precios WHERE id = 1);

SELECT setval(pg_get_serial_sequence('precios.lista_precios', 'id'),
              GREATEST((SELECT COALESCE(MAX(id), 1) FROM precios.lista_precios), 1));

CREATE TABLE IF NOT EXISTS precios.insumo_precios (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    insumo_id     BIGINT NOT NULL REFERENCES precios.insumos(id) ON DELETE CASCADE,
    -- NOTA (drift vs SQLite): db/precios.sql no tiene este ON DELETE CASCADE. Hoy es
    -- inocuo porque nadie borra insumos. Reconciliar ambos esquemas si se añade borrado.
    precio        DOUBLE PRECISION NOT NULL,
    fuente        TEXT,
    clasificacion TEXT,
    fecha         TEXT,
    vigente       INTEGER NOT NULL DEFAULT 1,
    creado_por    TEXT,
    lista_id      BIGINT NOT NULL DEFAULT 1 REFERENCES precios.lista_precios(id)
);
CREATE INDEX IF NOT EXISTS idx_precio_ins ON precios.insumo_precios(insumo_id, vigente);

-- Migración de una base preexistente (tabla ya creada sin lista_id): añade la
-- columna con el mismo DEFAULT/REFERENCES que el CREATE TABLE canónico de arriba.
-- Inocuo en una base nueva (la columna ya existe). El índice va DESPUÉS: no se
-- puede indexar una columna que todavía no existe (mismo bug que hubo en SQLite).
ALTER TABLE precios.insumo_precios
    ADD COLUMN IF NOT EXISTS lista_id BIGINT NOT NULL DEFAULT 1
    REFERENCES precios.lista_precios(id);

CREATE INDEX IF NOT EXISTS idx_precio_ins_lista
    ON precios.insumo_precios(insumo_id, lista_id, vigente);

CREATE TABLE IF NOT EXISTS precios.meta (
    clave TEXT PRIMARY KEY,
    valor TEXT
);
