"""
Contratos de almacenamiento, separados por dominio.

Hoy los implementan PreciosDB y ApusDB (SQLite). Mañana, un backend de nube
(p. ej. Postgres) implementa estos mismos Protocols y el resto del programa no cambia.
"""
from __future__ import annotations

from typing import Iterable, Optional, Protocol, runtime_checkable

from apu_tool.nucleo.models import (
    Apu, ApuComponent, CorridaItemRow, CorridaMeta, DePricedApu, Insumo,
)


@runtime_checkable
class RepositorioPrecios(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_insumos(self, insumos: Iterable[Insumo]) -> int: ...
    def get_candidatos(self, codigo: str) -> list[Insumo]: ...
    def get_insumo_por_id(self, insumo_id: int) -> Optional[Insumo]: ...
    def set_precio(self, codigo: str, precio: float, fuente: str = "",
                   fecha: Optional[str] = None, nombre: Optional[str] = None) -> None: ...
    def set_precio_por_id(self, insumo_id: int, precio: float, fuente: str = "",
                          fecha: Optional[str] = None) -> None: ...
    def price_history(self, codigo: str, nombre: Optional[str] = None) -> list[dict]: ...
    def list_insumos(self, q=None, grupo=None, fuente=None,
                     clasificacion: Optional[str] = None,
                     limit: int = 100, offset: int = 0) -> tuple[list[Insumo], int]: ...
    def grupos(self) -> list[str]: ...
    def fuentes(self) -> list[str]: ...
    def search_insumos(self, texto: str, limit: int = 20) -> list[Insumo]: ...
    def search_insumos_por_palabras(self, palabras: list[str],
                                    limit: int = 60) -> list[Insumo]: ...
    def counts(self) -> dict[str, int]: ...
    def set_meta(self, clave: str, valor: str) -> None: ...
    def get_meta(self) -> dict[str, str]: ...


@runtime_checkable
class RepositorioApus(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_apus(self, apus: Iterable[Apu]) -> int: ...
    def insert_components(self, comps: Iterable[ApuComponent]) -> int: ...
    def all_apus(self) -> list[Apu]: ...
    def apu_index(self) -> list[tuple[str, str, str]]: ...
    def get_apu(self, codigo: str, shift: str) -> Optional[Apu]: ...
    def search_apus(self, texto: str, limit: int = 20) -> list[Apu]: ...
    def get_components(self, apu_codigo: str, shift: str) -> list[ApuComponent]: ...
    def get_depriced_apu(self, codigo: str, shift: str) -> Optional[DePricedApu]: ...
    def counts(self) -> dict[str, int]: ...
    def set_meta(self, clave: str, valor: str) -> None: ...
    def get_meta(self) -> dict[str, str]: ...


@runtime_checkable
class RepositorioCorridas(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def crear_corrida(self, meta: CorridaMeta) -> int: ...
    def guardar_items(self, corrida_id: int, items: list[CorridaItemRow]) -> int: ...
    def get_corrida(self, corrida_id: int) -> Optional[CorridaMeta]: ...
    def get_items(self, corrida_id: int) -> list[CorridaItemRow]: ...
    def get_item(self, corrida_id: int, seq: int) -> Optional[CorridaItemRow]: ...
    def actualizar_eleccion(self, corrida_id: int, seq: int, *, status: str,
                            apu_codigo: Optional[str], apu_nombre: str, unidad: str,
                            shift: str, origen: str, confianza: float,
                            explicacion: str, componentes: list[dict]) -> None: ...
    def set_cuadro(self, corrida_id: int, path: str) -> None: ...
    def set_estado(self, corrida_id: int, estado: str) -> None: ...
    def listar_corridas(self) -> list[CorridaMeta]: ...
    def eliminar_corrida(self, corrida_id: int) -> bool: ...
    def counts(self) -> dict[str, int]: ...
