"""
Contratos de almacenamiento, separados por dominio.

Hoy los implementan PreciosDB y ApusDB (SQLite). Mañana, un backend de nube
(p. ej. Postgres) implementa estos mismos Protocols y el resto del programa no cambia.
"""
from __future__ import annotations

from typing import Iterable, Optional, Protocol, runtime_checkable

from apu_tool.nucleo.models import Apu, ApuComponent, DePricedApu, Insumo


@runtime_checkable
class RepositorioPrecios(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_insumos(self, insumos: Iterable[Insumo]) -> int: ...
    def get_insumo(self, codigo: str) -> Optional[Insumo]: ...
    def set_precio(self, codigo: str, precio: float, fuente: str = "",
                   fecha: Optional[str] = None) -> None: ...
    def price_history(self, codigo: str) -> list[dict]: ...
    def search_insumos(self, texto: str, limit: int = 20) -> list[Insumo]: ...
    def search_insumos_por_palabras(self, palabras: list[str],
                                    limit: int = 60) -> list[Insumo]: ...
    def counts(self) -> dict[str, int]: ...
    def set_meta(self, clave: str, valor: str) -> None: ...
    def get_meta(self) -> dict[str, str]: ...


@runtime_checkable
class RepositorioApus(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_apus(self, apus: Iterable[Apu]) -> int: ...
    def insert_components(self, comps: Iterable[ApuComponent]) -> int: ...
    def all_apus(self) -> list[Apu]: ...
    def apu_index(self) -> list[tuple[str, str, str]]: ...
    def get_apu(self, codigo: str, shift: str) -> Optional[Apu]: ...
    def search_apus(self, texto: str, limit: int = 20) -> list[Apu]: ...
    def get_components(self, apu_codigo: str, shift: str) -> list[ApuComponent]: ...
    def get_depriced_apu(self, codigo: str, shift: str) -> Optional[DePricedApu]: ...
    def counts(self) -> dict[str, int]: ...
    def set_meta(self, clave: str, valor: str) -> None: ...
    def get_meta(self) -> dict[str, str]: ...
