"""
Contratos de almacenamiento, separados por dominio.

Hoy los implementan PreciosDB y ApusDB (SQLite). Mañana, un backend de nube
(p. ej. Postgres) implementa estos mismos Protocols y el resto del programa no cambia.
"""
from __future__ import annotations

from typing import Iterable, Optional, Protocol, runtime_checkable

from apu_tool.nucleo.models import (
    Apu, ApuComponent, Carpeta, CorridaItemRow, CorridaMeta, DePricedApu, EventoAuditoria,
    Insumo, ListaPrecios, Perfil,
)


class CorridaEliminada(Exception):
    """Se intentó agregar un ítem a una corrida que ya no existe (la borraron o se
    reseteó durante el armado). Señala que el armado debe cancelarse limpio, en vez
    de propagar un error de integridad de la base."""

    def __init__(self, corrida_id: int):
        super().__init__(f"La corrida {corrida_id} fue eliminada durante el armado.")
        self.corrida_id = corrida_id


@runtime_checkable
class RepositorioPrecios(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_insumos(self, insumos: Iterable[Insumo]) -> int: ...
    def crear_insumo(self, insumo: Insumo, conn=None, creado_por: Optional[str] = None,
                     lista_id: Optional[int] = None) -> int: ...
    def get_candidatos(self, codigo: str, lista_id: Optional[int] = None) -> list[Insumo]: ...
    def get_candidatos_bulk(self, codigos: Iterable[str],
                            lista_id: Optional[int] = None) -> dict[str, list[Insumo]]:
        """Como get_candidatos pero para muchos códigos en UNA consulta (optimización).
        Devuelve {codigo: [candidatos...]} con la misma semántica que llamarlo 1x1."""
        ...
    def get_insumo_por_id(self, insumo_id: int,
                          lista_id: Optional[int] = None) -> Optional[Insumo]: ...
    def set_precio(self, codigo: str, precio: float, fuente: str = "",
                   fecha: Optional[str] = None, nombre: Optional[str] = None) -> None: ...
    def set_precio_por_id(self, insumo_id: int, precio: float, fuente: str = "",
                          fecha: Optional[str] = None, conn=None,
                          creado_por: Optional[str] = None,
                          lista_id: Optional[int] = None) -> None: ...
    def price_history(self, codigo: str, nombre: Optional[str] = None,
                      lista_id: Optional[int] = None) -> list[dict]: ...
    def list_insumos(self, q=None, grupo=None, fuente=None,
                     clasificacion: Optional[str] = None,
                     limit: int = 100, offset: int = 0,
                     lista_id: Optional[int] = None,
                     sin_precio: bool = False) -> tuple[list[Insumo], int]:
        """Catálogo COMPLETO con el precio vigente en `lista_id` (None = Principal).
        Los insumos sin tarifa en esa lista vienen con precio 0 y `sin_precio=True`.
        `sin_precio=True` es excluyente con `fuente` y `clasificacion` (ValueError)."""
        ...
    def grupos(self) -> list[str]: ...
    def fuentes(self, lista_id: Optional[int] = None) -> list[str]: ...
    def set_oculto(self, insumo_id: int, oculto: bool, conn=None) -> None:
        """Marca (o desmarca) un insumo como oculto — no se borra, solo se filtra
        de list_insumos/search_insumos*/grupos/fuentes."""
        ...
    def todos_no_ocultos(self) -> list[tuple[int, str, str]]:
        """(id, codigo, nombre) de todos los insumos con oculto=false."""
        ...
    def identidades_en_conflicto(self, codigo: str,
                                 nombre_norm: str) -> list[tuple[str, str, bool]]:
        """`(codigo, nombre, oculto)` de los insumos cuyo código O `nombre_norm` coincide.

        Los dos lados del chequeo de duplicados del alta (`servicio/autoria.py`) en una
        sola consulta. Incluye los ocultos a propósito: `get_candidatos` no filtra
        `oculto`, o sea que el motor de precios los ve, y un código repetido con uno
        oculto deja el cruce igual de ambiguo que con uno visible."""
        ...
    def search_insumos(self, texto: str, limit: int = 20) -> list[Insumo]: ...
    def search_insumos_por_palabras(self, palabras: list[str],
                                    limit: int = 60) -> list[Insumo]: ...

    def counts(self) -> dict[str, int]:
        """`insumos` (todas las filas), `insumo_precios` y `insumos_visibles`.

        `insumos` incluye los ocultos: lo usan los guards de seed. `insumos_visibles`
        excluye `oculto = 1` y es la que se le muestra al usuario."""
        ...
    def set_meta(self, clave: str, valor: str) -> None: ...
    def get_meta(self) -> dict[str, str]: ...
    def descripcion(self) -> str:
        """Identidad legible del backend (para `status`), agnóstica de SQLite/Postgres."""
        ...

    # --- listas de precios (tarifas). La id config.LISTA_PRINCIPAL_ID es 'Principal' ---
    def listar_listas(self) -> list[ListaPrecios]: ...
    def get_lista(self, lista_id: int) -> Optional[ListaPrecios]: ...
    def crear_lista(self, nombre: str, creado_por: Optional[str] = None,
                    conn=None) -> int:
        """Crea una lista. ValueError si el nombre está vacío o ya existe (sin
        distinguir mayúsculas)."""
        ...
    def renombrar_lista(self, lista_id: int, nombre: str, conn=None) -> None:
        """ValueError si la lista no existe, si el nombre choca, o si es la Principal
        (intocable: es el ancla del invariante lista_id=None == Principal)."""
        ...


@runtime_checkable
class RepositorioApus(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_apus(self, apus: Iterable[Apu]) -> int: ...
    def insert_components(self, comps: Iterable[ApuComponent]) -> int: ...
    def crear_apu(self, apu: Apu, componentes: list[ApuComponent], conn=None) -> None: ...
    def editar_apu(self, apu: Apu, componentes: list[ApuComponent], conn=None) -> None:
        """Edita cabecera (nombre/unidad/grupo) y REEMPLAZA la composición de un APU
        existente. Identidad (codigo, shift) inmutable. ValueError si no existe."""
        ...
    def borrar_apu(self, codigo: str, shift: str, conn=None) -> bool:
        """Borra componentes + cabecera de un APU. False si no existía."""
        ...
    def list_apus(self, q: Optional[str] = None, grupo: Optional[str] = None,
                  shift: Optional[str] = None, limit: int = 100,
                  offset: int = 0) -> tuple[list[Apu], int]: ...
    def all_apus(self) -> list[Apu]: ...
    def apu_index(self) -> list[tuple[str, str, str]]: ...
    def get_apu(self, codigo: str, shift: str) -> Optional[Apu]: ...
    def search_apus(self, texto: str, limit: int = 20) -> list[Apu]: ...
    def grupos(self) -> list[str]: ...
    def get_components(self, apu_codigo: str, shift: str) -> list[ApuComponent]: ...
    def get_components_bulk(self, claves: Iterable[tuple[str, str]]
                            ) -> dict[tuple[str, str], list[ApuComponent]]:
        """Como get_components pero para muchos (codigo, shift) en UNA consulta.
        Devuelve {(codigo, shift): [componentes...]} para las claves halladas."""
        ...
    def component_counts(self) -> dict[tuple[str, str], int]: ...
    def componentes_subapu_candidatos(self) -> list[dict]:
        """Componentes tipo='insumo' cuyo código es un APU (candidatos a sub-APU)."""
        ...
    def set_componente_subapu(self, apu_codigo: str, shift: str, seq: int,
                              ref_shift: str, conn=None) -> None:
        """Marca un componente como sub-APU (tipo='apu') con su turno de referencia."""
        ...
    def pares_insumo_en_uso(self) -> list[tuple[str, str]]:
        """(insumo_codigo, insumo_nombre) distintos de cada componente tipo='insumo'."""
        ...
    def get_depriced_apu(self, codigo: str, shift: str) -> Optional[DePricedApu]: ...
    def componentes_para_integridad(self) -> list[tuple[str, str]]:
        """(insumo_codigo, insumo_nombre) de cada componente con código no vacío.
        Para el chequeo de integridad APU→insumo, sin SQL crudo en el dominio."""
        ...
    def counts(self) -> dict[str, int]: ...
    def set_meta(self, clave: str, valor: str) -> None: ...
    def get_meta(self) -> dict[str, str]: ...
    def descripcion(self) -> str:
        """Identidad legible del backend (para `status`), agnóstica de SQLite/Postgres."""
        ...


@runtime_checkable
class RepositorioCorridas(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def crear_corrida(self, meta: CorridaMeta) -> int: ...
    def guardar_items(self, corrida_id: int, items: list[CorridaItemRow]) -> int: ...
    def agregar_item(self, corrida_id: int, fila: CorridaItemRow) -> None:
        """Inserta un ítem (armado incremental). Lanza CorridaEliminada si la
        corrida ya no existe."""
        ...
    def borrar_items(self, corrida_id: int, seqs: Iterable[int], conn=None) -> int:
        """Borra los ítems indicados y devuelve cuántos borró. Los seq que no existen
        se ignoran. NO renumera lo que queda: el seq es identidad (URL del ítem y clave
        del snapshot), así que renumerar casaría snapshots con la línea equivocada."""
        ...
    def get_corrida(self, corrida_id: int) -> Optional[CorridaMeta]: ...
    def get_items(self, corrida_id: int) -> list[CorridaItemRow]: ...
    def get_item(self, corrida_id: int, seq: int) -> Optional[CorridaItemRow]: ...
    def actualizar_eleccion(self, corrida_id: int, seq: int, *, status: str,
                            apu_codigo: Optional[str], apu_nombre: str, unidad: str,
                            shift: str, origen: str, confianza: float,
                            explicacion: str, componentes: list[dict]) -> None: ...
    def set_cuadro(self, corrida_id: int, path: str) -> None: ...
    def set_estado(self, corrida_id: int, estado: str) -> None: ...
    def set_duracion(self, corrida_id: int, duracion_ms: int) -> None: ...
    def set_modo(self, corrida_id: int, modo: str) -> None: ...
    def set_nombre(self, corrida_id: int, nombre: str) -> None: ...
    def set_snapshot(self, corrida_id: int, seq: int, payload: dict) -> None: ...
    def get_snapshots(self, corrida_id: int) -> dict[int, dict]: ...
    def set_carpeta(self, corrida_id: int, carpeta_id: int, conn=None) -> None: ...
    def listar_corridas(self) -> list[CorridaMeta]: ...
    def eliminar_corrida(self, corrida_id: int, conn=None) -> bool: ...
    def counts(self) -> dict[str, int]: ...

    def contar_items_por_apu(self, apu_codigo: str) -> int:
        """Nº de ítems de corrida que referencian este apu_codigo (aviso al borrar)."""
        ...


@runtime_checkable
class RepositorioCarpetas(Protocol):
    def crear(self, nombre: str, parent_id: Optional[int] = None,
              creado_por: Optional[str] = None, conn=None) -> int: ...
    def get(self, carpeta_id: int) -> Optional[Carpeta]: ...
    def listar(self) -> list[Carpeta]: ...
    def renombrar(self, carpeta_id: int, nombre: str, conn=None) -> None: ...
    def mover(self, carpeta_id: int, parent_id: Optional[int], conn=None) -> None: ...
    def eliminar(self, carpeta_id: int, conn=None) -> bool: ...
    def contar_hijas(self, carpeta_id: int) -> int: ...
    def contar_corridas(self, carpeta_id: int) -> int: ...


@runtime_checkable
class RepositorioPerfiles(Protocol):
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def get(self, user_id: str) -> Optional[Perfil]: ...
    def upsert(self, perfil: Perfil, conn=None) -> None: ...

    def get_por_email(self, email: str) -> list[Perfil]:
        """Perfiles con ese email (comparado en minúsculas y sin espacios).

        Devuelve una LISTA porque `perfiles.email` no es UNIQUE: puede haber 0, 1 o
        varios. Quien decide qué hacer con el caso ambiguo es `servicio/auth.py`, no
        el repositorio."""
        ...

    def reasignar_user_id(self, viejo: str, nuevo: str, conn=None) -> bool:
        """Mueve un perfil a otro `user_id` (misma fila, nueva PK). Devuelve si aplicó.

        Es lo que hace la adopción por email cuando Supabase entrega un `user_id`
        nuevo para un usuario ya invitado. Se mueve y no se duplica: dos filas del
        mismo email descuadrarían el guard del último Admin activo, que cuenta filas.

        Devuelve `True` solo si el UPDATE movió una fila (`viejo` existía). El llamador
        (`_adoptar_por_email`) audita solo si esto da `True`: sin eso, una carrera (p.ej.
        varias llamadas paralelas tras un login) escribiría N filas de auditoría para un
        solo vínculo real."""
        ...

    def listar(self) -> list[Perfil]: ...
    def set_rol(self, user_id: str, rol: str, conn=None) -> None: ...
    def set_estado(self, user_id: str, estado: str, conn=None) -> None: ...
    def contar_admins_activos(self) -> int: ...

    def set_rol_protegido(self, user_id: str, rol: str, conn=None) -> bool:
        """UPDATE atómico del rol que NO deja el sistema sin admin activo.
        Devuelve True si aplicó, False si lo bloqueó el guard (o el usuario no existe)."""
        ...

    def set_estado_protegido(self, user_id: str, estado: str, conn=None) -> bool:
        """UPDATE atómico del estado con el mismo guard de último-admin. Devuelve si aplicó."""
        ...


@runtime_checkable
class RepositorioAuditoria(Protocol):
    def registrar(self, conn, evento: EventoAuditoria) -> None:
        """Inserta un evento SOBRE la conexión dada (transaccional con la mutación).
        NUNCA abre su propia conexión."""
        ...

    def listar(self, *, user_id: Optional[str] = None, accion: Optional[str] = None,
               entidad_tipo: Optional[str] = None, desde: Optional[str] = None,
               hasta: Optional[str] = None, lote_id: Optional[str] = None,
               limit: int = 100, offset: int = 0) -> tuple[list[dict], int]:
        """Lectura paginada (abre su propia conexión). antes/despues/contexto ya
        parseados a objetos Python (dict/None). Orden ts desc."""
        ...
